### ISSUE TITLE
Hibernate Validator Version

### ISSUE THREAD

**Issue by pdang-ping** [bizaio/deepthought#2]
Currently the build is failing due to the newest version is 7.0 Alpha.

<hibernate-validator.version>6.1.2.Final</hibernate-validator.version>

I changed that in the pom.xml for it to build correctly.

**Comment by perlboy** [comment]
Hi @pdang-ping, oops, I noticed it for our other components but not deepthought. Have committed a fix in `master` and synced it with `develop`. Thanks for the pickup.
